// Code generated by "stringer -type Hook -trimprefix Hook"; DO NOT EDIT.

package shell

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HookPreRead-0]
	_ = x[HookPreExit-1]
	_ = x[HookInitialized-2]
}

const _Hook_name = "PreReadPreExitInitialized"

var _Hook_index = [...]uint8{0, 7, 14, 25}

func (i Hook) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Hook_index)-1 {
		return "Hook(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Hook_name[_Hook_index[idx]:_Hook_index[idx+1]]
}
