// Code generated by "stringer -type tokenType -trimprefix token"; DO NOT EDIT.

package interpreter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenError-0]
	_ = x[tokenEOF-1]
	_ = x[tokenSpace-2]
	_ = x[tokenText-3]
	_ = x[tokenSingleQuote-4]
	_ = x[tokenDoubleQuote-5]
	_ = x[tokenEscaped-6]
	_ = x[tokenRedirect-7]
	_ = x[tokenAppend-8]
}

const _tokenType_name = "ErrorEOFSpaceTextSingleQuoteDoubleQuoteEscapedRedirectAppend"

var _tokenType_index = [...]uint8{0, 5, 8, 13, 17, 28, 39, 46, 54, 60}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
